### ISSUE TITLE
Clarify terraform version requirement

### ISSUE THREAD

**Issue by blkperl** [Yelp/terraform-provider-signalform#10]
The readme states "Please note that this provider only works with terraform 0.9." but in testing it appears to be working on Terraform v0.11.2. Is 0.9 a minimum requirement, the only version being tested or are their known issues on the new versions?

**Comment by poros** [comment]
You are right, that may cause a bit of confusion. That number is the terraform version we test the provider against and the one we use the provider with. It doesn't necessarily means that it won't compile with newer of older versions, just that we don't guarantee it does.

In addition, the number has drifted from reality, since we are now testing against terraform 0.10.
